- hosts: all
  tasks:
          - name: Docker repository
            yum_repository:
                    description: "repo for docker"
                    name: "docker"
                    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                    gpgcheck: false

          - name: Installing Docker software
            yum:
                 name: "docker-ce-18.09.1-3.el7.x86_64"
                 state: present

          - name: startingg docker services
            service:
                 name: docker
                 state: started
          - pip:
                 name: docker-py

          - name: Pulling the HTTPD docker image
            docker_image:
                 name: httpd
                 source: pull
          - name: copying file into home
            copy:
                 src: web.html
                 dest: /task
          - name: creating a docker container for webserver
            docker_container:
                name: MyWebSever
                image: httpd
                state: started
                ports:
                -"8080:80"
                volumes:
                - /task:/user/local/apache2/htdocs/
                
                
